spring:
  application:
    name: 'basketballvillage'

  jwt:
    secret: ${JWT_SECRET}

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://basketball-village.cjqcu8cietug.ap-northeast-2.rds.amazonaws.com:3308/basketballvillage #내 로컬 mysql
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
#    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    open-in-view: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: -1
  api-docs:
    path: /api
    show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**
