spring:
  jwt:
    secret: 'ThisIsTestSecretCode'
  application:
    name: 'basketballvillage'

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/basketballvillage?characterEncoding=UTF-8&serverTimezone=UTC #내 로컬 mysql
    username: root
    password: 1234

  jpa:
#    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        hibernate:
          "[format_sql]": true            #SQL 보기 좋게 출력
          "[user_sql_comments]": true     #SQL 생성시 주석 포함
          "[highlight_sql]": true         #SQL 색깔
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false